SELECT * FROM LINE WHERE INV_NUMBER = 9002;

-- Clerk part: entering and fixing sales for invoice 9002

USE CH07_SALECO;

INSERT INTO INVOICE (INV_NUMBER, CUS_CODE, INV_DATE)
VALUES (9002, 10016, '2025-11-29 14:30:00');

INSERT INTO LINE (INV_NUMBER, LINE_NUMBER, P_CODE, LINE_UNITS, LINE_PRICE)
VALUES (9002, 1, '13-Q2/P2', 2, 14.99);

INSERT INTO LINE (INV_NUMBER, LINE_NUMBER, P_CODE, LINE_UNITS, LINE_PRICE)
VALUES (9002, 2, '14-Q1/L3', 1, 17.49);

UPDATE LINE
SET LINE_UNITS = 3
WHERE INV_NUMBER = 9002 AND LINE_NUMBER = 1;

DELETE FROM LINE
WHERE INV_NUMBER = 9002 AND LINE_NUMBER = 2;

SELECT l.INV_NUMBER,
       l.LINE_NUMBER,
       p.P_DESCRIPT,
       l.LINE_UNITS,
       l.LINE_PRICE,
       (l.LINE_UNITS * l.LINE_PRICE) AS Line_Total
FROM LINE l
JOIN PRODUCT p ON l.P_CODE = p.P_CODE
WHERE l.INV_NUMBER = 9002;
